export const HOME_VIEW = "HOME_VIEW";
export const WORKOUT_ADDER_VIEW = "WORKOUT_ADDER_VIEW";
export const EQUIPMENT_VIEW = "EQUIPMENT_VIEW";
export const EQUIPMENT_ADDER_VIEW = "EQUIPMENT_ADDER_VIEW";
export const POSTED_VIEW = "POSTED_VIEW";
export const SET_ADDER_VIEW = "SET_ADDER_VIEW";

